apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer
  labels:
    app: explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer
  template:
    metadata:
      labels:
        app: explorer
    spec:
      serviceAccountName: default
      {{- with .Values }}
      containers:
        - name: main
          image: "{{ required "A valid repo entry required!" .repo }}:{{ required "A valid tag entry required!" .tag }}"
          imagePullPolicy: Always
          env:
          {{- with .env }}
          - name: DIEMX_CHAIN
            value: {{ required "chain required" .chain }}
          - name: DIEMX_ENV
            value: {{ required "env required" .env }}
          - name: DIEMX_BASE_URL
            value: {{ required "base_url required" .base_url }}
          - name: DIEMX_GRAPHQL_URL
            value: {{ required "graphql_url required" .graphql_url }}
          - name: DIEMX_BLOCKCHAIN_URL
            value: {{ required "blockchain_jsonrpc_url required" .blockchain_jsonrpc_url }}
          - name: DIEMX_BLOCKCHAIN_API_URL
            value: {{ required "blockchain_restapi_url required" .blockchain_restapi_url }}
          {{- end }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: explorer
  labels:
    app: explorer
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: explorer
