export default {
  data: {
    transactions: [
      {
        version: 502,
        commit_timestamp: '2021-04-19 00:30:00.000000 +00:00',
        txn_type: 3,
        status: 1,
        gas_used: 10,
        sender: null,
        sequence_number: null,
        public_key: null,
        chain_id: null,
        max_gas_amount: null,
        gas_unit_price: null,
        gas_currency: null,
        expiration_timestamp: null
      },
      {
        version: 503,
        commit_timestamp: '2021-04-24 00:30:00.000000 +00:00',
        txn_type: 3,
        status: 1,
        gas_used: 10,
        sender: null,
        sequence_number: null,
        public_key: null,
        chain_id: null,
        max_gas_amount: null,
        gas_unit_price: null,
        gas_currency: null,
        expiration_timestamp: null
      },
      {
        version: 504,
        commit_timestamp: '2021-04-28 00:30:00.000000 +00:00',
        txn_type: 3,
        status: 1,
        gas_used: 10,
        sender: null,
        sequence_number: null,
        public_key: null,
        chain_id: null,
        max_gas_amount: null,
        gas_unit_price: null,
        gas_currency: null,
        expiration_timestamp: null
      },
      {
        version: 505,
        commit_timestamp: '2021-05-02 00:30:00.000000 +00:00',
        txn_type: 3,
        status: 1,
        gas_used: 10,
        sender: null,
        sequence_number: null,
        public_key: null,
        chain_id: null,
        max_gas_amount: null,
        gas_unit_price: null,
        gas_currency: null,
        expiration_timestamp: null
      },
      {
        version: 506,
        commit_timestamp: '2021-05-09 00:30:00.000000 +00:00',
        txn_type: 3,
        status: 1,
        gas_used: 10,
        sender: null,
        sequence_number: null,
        public_key: null,
        chain_id: null,
        max_gas_amount: null,
        gas_unit_price: null,
        gas_currency: null,
        expiration_timestamp: null
      },
      {
        version: 507,
        commit_timestamp: '2021-05-14 00:30:00.000000 +00:00',
        txn_type: 3,
        status: 1,
        gas_used: 10,
        sender: null,
        sequence_number: null,
        public_key: null,
        chain_id: null,
        max_gas_amount: null,
        gas_unit_price: null,
        gas_currency: null,
        expiration_timestamp: null
      },
      {
        version: 1,
        commit_timestamp: '2020-12-27 00:15:47.000000 +00:00',
        txn_type: 3,
        status: 1,
        gas_used: 10,
        sender: null,
        sequence_number: null,
        public_key: null,
        chain_id: null,
        max_gas_amount: null,
        gas_unit_price: null,
        gas_currency: null,
        expiration_timestamp: null
      },
      {
        version: 14,
        commit_timestamp: '2021-01-30 17:17:09.000000 +00:00',
        txn_type: 3,
        status: 1,
        gas_used: 10,
        sender: null,
        sequence_number: null,
        public_key: null,
        chain_id: null,
        max_gas_amount: null,
        gas_unit_price: null,
        gas_currency: null,
        expiration_timestamp: null
      },
      {
        version: 26,
        commit_timestamp: '2021-02-25 14:47:40.000000 +00:00',
        txn_type: 3,
        status: 1,
        gas_used: 10,
        sender: null,
        sequence_number: null,
        public_key: null,
        chain_id: null,
        max_gas_amount: null,
        gas_unit_price: null,
        gas_currency: null,
        expiration_timestamp: null
      },
      {
        version: 59,
        commit_timestamp: '2021-03-26 19:37:39.000000 +00:00',
        txn_type: 3,
        status: 1,
        gas_used: 10,
        sender: null,
        sequence_number: null,
        public_key: null,
        chain_id: null,
        max_gas_amount: null,
        gas_unit_price: null,
        gas_currency: null,
        expiration_timestamp: null
      }
    ]
  }
}
